name: Mentora
description: "Mentora is a mental health and well-being app designed to support individuals dealing with stress, anxiety, or other emotional challenges. It offers mood tracking, guided exercises, and personalized self-care tools to help users build healthy habits and improve overall wellness."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  my_icons:
    git:
      url: https://github.com/Saurav-Rana-June/my_packages.git
      path: my_icons
      ref: main
  my_spacing:
    git:
      url: https://github.com/Saurav-Rana-June/my_packages.git
      path: my_spacing
      ref: my_spacing
  pinput: ^6.0.1
  flutter_svg: ^2.2.3
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  cached_network_image: ^3.4.1
  percent_indicator: ^4.2.5
  dio: ^5.11.0
  get_storage: ^2.1.1
  logger: ^2.7.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  http_parser: ^4.0.2
  just_audio: ^0.10.6
  soundcloud_explode_dart: ^1.1.0
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/light_mode_ss/
    - assets/gifs/
    - assets/moods/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700

    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf

    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf

    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/fa-light-300.ttf

    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
